# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='publish_date',
            field=models.DateTimeField(default='2017-08-10 00:04', verbose_name='publish date'),
            preserve_default=False,
        ),
    ]
